test_that("vtree test 1",{
  expect_identical(vtree(FakeData,"Severity Sex",getscript=TRUE),
"digraph vtree {\ngraph [layout = dot, compound=true, nodesep=0.1, ranksep=0.5, fontsize=12]\nnode [fontname = Helvetica, fontcolor = black,shape = rectangle, color = black,margin=0.1]\nrankdir=LR;\nNode_L0[style=invisible]\nNode_L1[label=<<FONT POINT-SIZE=\"18\"><FONT COLOR=\"#DE2D26\"><B>Severity  </B></FONT></FONT><BR/>> shape=none margin=0]\nNode_L2[label=<<FONT POINT-SIZE=\"18\"><FONT COLOR=\"#3182BD\"><B>Sex  </B></FONT></FONT><BR/>> shape=none margin=0]\n\nedge[style=invis];\nNode_L0->Node_L1->Node_L2\n\nedge[style=solid]\nNode_1->Node_2 Node_1->Node_3 Node_1->Node_4 Node_1->Node_5\nNode_2->Node_6 Node_2->Node_7\nNode_3->Node_8 Node_3->Node_9\nNode_4->Node_10 Node_4->Node_11\nNode_5->Node_12 Node_5->Node_13\n\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_2[label=<Mild<BR/>19 (48%)> color=black style=\"rounded,filled\" fillcolor=<#FEE0D2>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_3[label=<Moderate<BR/>16 (40%)> color=black style=\"rounded,filled\" fillcolor=<#FC9272>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_4[label=<Severe<BR/>5 (12%)> color=black style=\"rounded,filled\" fillcolor=<#DE2D26>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_5[label=<NA<BR/>6> color=black style=\"rounded,filled\" fillcolor=<white>  ]\nNode_6[label=<F<BR/>11 (58%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_7[label=<M<BR/>8 (42%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_8[label=<F<BR/>11 (69%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_9[label=<M<BR/>5 (31%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_10[label=<F<BR/>2 (40%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_11[label=<M<BR/>3 (60%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_12[label=<F<BR/>3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_13[label=<M<BR/>3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\n\n}\n"
  )})

test_that("vtree test 2",{
  expect_identical(vtree(FakeData,"Severity Sex",horiz=FALSE,plain=TRUE,getscript=TRUE),
"digraph vtree {\ngraph [layout = dot, compound=true, nodesep=0.46, ranksep=0.5, fontsize=12]\nnode [fontname = Helvetica, fontcolor = black,shape = rectangle, color = black,margin=0.18]\nNode_L0[style=invisible]\nNode_L1[label=<<FONT POINT-SIZE=\"18\">Severity</FONT><BR/>> shape=none margin=0]\nNode_L2[label=<<FONT POINT-SIZE=\"18\">Sex</FONT><BR/>> shape=none margin=0]\n\nedge[style=invis];\nNode_L0->Node_L1->Node_L2\n\nedge[style=solid]\nNode_1->Node_2 Node_1->Node_3 Node_1->Node_4 Node_1->Node_5\nNode_2->Node_6 Node_2->Node_7\nNode_3->Node_8 Node_3->Node_9\nNode_4->Node_10 Node_4->Node_11\nNode_5->Node_12 Node_5->Node_13\n\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_2[label=<Mild<BR/>19 (48%)> color=black style=\"rounded,filled\" fillcolor=<#C6DBEF>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_3[label=<Moderate<BR/>16 (40%)> color=black style=\"rounded,filled\" fillcolor=<#C6DBEF>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_4[label=<Severe<BR/>5 (12%)> color=black style=\"rounded,filled\" fillcolor=<#C6DBEF>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_5[label=<NA<BR/>6> color=black style=\"rounded,filled\" fillcolor=<#C6DBEF>  ]\nNode_6[label=<F<BR/>11 (58%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_7[label=<M<BR/>8 (42%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_8[label=<F<BR/>11 (69%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_9[label=<M<BR/>5 (31%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_10[label=<F<BR/>2 (40%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_11[label=<M<BR/>3 (60%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_12[label=<F<BR/>3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\nNode_13[label=<M<BR/>3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#9ECAE1>  ]\n\n}\n"
  )})
  
test_that("vtree test 3",{
  expect_identical(vtree(FakeData,"Severity Sex",showlegend=TRUE,shownodelabels=FALSE,getscript=TRUE),
"digraph vtree {\ngraph [layout = dot, compound=true, nodesep=0.1, ranksep=0.5, fontsize=12]\nnode [fontname = Helvetica, fontcolor = black,shape = rectangle, color = black,margin=0.1]\nrankdir=LR;\nNode_L0[style=invisible]\nNode_L1[label=<<FONT POINT-SIZE=\"18\"><FONT COLOR=\"#DE2D26\"><B>Severity  </B></FONT></FONT><BR/><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE='30' COLOR='#FEE0D2'>&#x25CF;</FONT>&nbsp;Mild, 19 (48%)<BR ALIGN=\"LEFT\" /><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE='30' COLOR='#FC9272'>&#x25CF;</FONT>&nbsp;Moderate, 16 (40%)<BR ALIGN=\"LEFT\" /><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE='30' COLOR='#DE2D26'>&#x25CF;</FONT>&nbsp;Severe, 5 (12%)<BR ALIGN=\"LEFT\" /><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE=\"20\" COLOR=\"black\">&#x25EF;</FONT>&nbsp;&nbsp;NA, 6 <BR ALIGN=\"LEFT\" />> shape=none margin=0]\nNode_L2[label=<<FONT POINT-SIZE=\"18\"><FONT COLOR=\"#3182BD\"><B>Sex  </B></FONT></FONT><BR/><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE='30' COLOR='#DEEBF7'>&#x25CF;</FONT>&nbsp;F, 27 (59%)<BR ALIGN=\"LEFT\" /><FONT POINT-SIZE=\"1\"> </FONT><BR ALIGN=\"LEFT\" /><FONT POINT-SIZE='30' COLOR='#3182BD'>&#x25CF;</FONT>&nbsp;M, 19 (41%) <BR ALIGN=\"LEFT\" />> shape=none margin=0]\n\nedge[style=invis];\nNode_L0->Node_L1->Node_L2\n\nedge[style=solid]\nNode_1->Node_2 Node_1->Node_3 Node_1->Node_4 Node_1->Node_5\nNode_2->Node_6 Node_2->Node_7\nNode_3->Node_8 Node_3->Node_9\nNode_4->Node_10 Node_4->Node_11\nNode_5->Node_12 Node_5->Node_13\n\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_2[label=<19 (48%)> color=black style=\"rounded,filled\" fillcolor=<#FEE0D2>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_3[label=<16 (40%)> color=black style=\"rounded,filled\" fillcolor=<#FC9272>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_4[label=<5 (12%)> color=black style=\"rounded,filled\" fillcolor=<#DE2D26>  ]\nNode_1[label=<46> color=black style=\"rounded,filled\" fillcolor=<#EFF3FF>]\nNode_5[label=<6> color=black style=\"rounded,filled\" fillcolor=<white>  ]\nNode_6[label=<11 (58%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_7[label=<8 (42%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_8[label=<11 (69%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_9[label=<5 (31%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_10[label=<2 (40%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_11[label=<3 (60%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\nNode_12[label=<3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#DEEBF7>  ]\nNode_13[label=<3 (50%)> color=black style=\"rounded,filled\" fillcolor=<#3182BD>  ]\n\n}\n"
  )})
  
test_that("vtree test 100",{
  expect_identical(dput(vtree(FakeData,"Severity Age Pre Post",check.is.na=TRUE,ptable=TRUE)),
structure(list(n = c(1, 1, 1, 1, 2, 4, 4, 32), pct = c(2, 2, 
2, 2, 4, 9, 9, 70), MISSING_Severity = c("not N/A", "not N/A", 
"not N/A", "not N/A", "N/A", "N/A", "not N/A", "not N/A"), MISSING_Age = c("N/A", 
"not N/A", "not N/A", "not N/A", "N/A", "not N/A", "N/A", "not N/A"
), MISSING_Pre = c("N/A", "N/A", "N/A", "not N/A", "not N/A", 
"not N/A", "not N/A", "not N/A"), MISSING_Post = c("not N/A", 
"N/A", "not N/A", "N/A", "not N/A", "not N/A", "not N/A", "not N/A"
)), row.names = c(NA, -8L), class = "data.frame")
  )}) 
