---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vtree)
```

```{r}
(v1 <- vtree(FakeData,"Severity Sex"))
```

```{r}
grVizToPNG(v1,width=3000,folder="png")
```

```{r}
(v2 <- vtree(FakeData,"Group",horiz=FALSE))
```

```{r}
grVizToPNG(v2,width=3000,folder="png")
```

```{r}
(v3 <- vtree(FakeData,"Severity Sex",
  showlegend=TRUE,sameline=TRUE))
```

```{r}
grVizToPNG(v3,width=3000,folder="png")
```

```{r}
(v4 <- vtree(FakeData,"Severity Sex",
  prune=list(Severity=c("Mild","Moderate"))))
```

```{r}
grVizToPNG(v4,width=3000,folder="png")
```

```{r}
(v5 <- vtree(FakeData,"Severity Sex",
  prunebelow=list(Severity=c("Mild","Moderate"))))
```

```{r}
grVizToPNG(v5,width=3000,folder="png")
```

```{r}
(v6 <- vtree(FakeData,"Severity Sex",
  keep=list(Severity=c("Mild","NA"))))
```

```{r}
grVizToPNG(v6,width=3000,folder="png")
```

```{r}
(v7 <- vtree(FakeData,"Severity Sex",
  follow=list(Severity=c("Mild","NA"))))
```

```{r}
grVizToPNG(v7,width=3000,folder="png")
```

```{r}
(v8 <- vtree(FakeData,"Group Severity",sameline=TRUE,
  text=list(Severity=c(Mild="\n*or none*"))))
```

```{r}
grVizToPNG(v8,width=3000,folder="png")
```

```{r}
(v9 <- vtree(FakeData,"Severity Age Pre Post",check.is.na=TRUE))
```

```{r}
grVizToPNG(v9,width=3000,folder="png")
```

```{r}
(v10 <- vtree(FakeData,"Severity",sameline=TRUE,
  summary="Score \n mean=%mean%"))
```

```{r}
grVizToPNG(v10,width=3000,folder="png")
```
